# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooktopper', '0003_auto_20170925_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestBurner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooktopper.Burner')),
                ('new_burner_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooktopper.BurnerState')),
                ('new_temperature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooktopper.Temperature')),
            ],
        ),
    ]
