# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooktopper', '0006_auto_20170930_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestburner',
            name='temperature_id',
        ),
        migrations.AddField(
            model_name='requestburner',
            name='new_temperature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooktopper.Temperature'),
            preserve_default=False,
        ),
    ]
