# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooktopper', '0007_auto_20170930_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestburner',
            name='hour',
        ),
        migrations.AddField(
            model_name='requestburner',
            name='time',
            field=models.IntegerField(default=1507072011),
            preserve_default=False,
        ),
    ]
