# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooktopper', '0008_auto_20171003_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestburner',
            old_name='time',
            new_name='new_time',
        ),
    ]
