# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooktopper', '0009_auto_20171005_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestburner',
            old_name='new_time',
            new_name='programmed_time',
        ),
    ]
