# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooktopper', '0010_auto_20171028_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmingdetails',
            old_name='programmed_hour',
            new_name='programmed_time',
        ),
        migrations.RemoveField(
            model_name='programmingdetails',
            name='programming_type',
        ),
        migrations.AddField(
            model_name='programmingdetails',
            name='new_burner_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooktopper.BurnerState'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProgrammingType',
        ),
    ]
