# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooktopper', '0011_auto_20171028_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestburner',
            name='programming_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
