# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooktopper', '0012_requestburner_programming_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stove',
            name='mac_address',
            field=models.CharField(default=0, max_length=45),
            preserve_default=False,
        ),
    ]
