# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooktopper', '0014_auto_20171102_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='programming',
            name='creation_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
