# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooktopper', '0015_programming_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='burner',
            name='time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
